# Generated by Django 4.0.5 on 2022-12-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_isstore_customer_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='activeOrders',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='customer',
            name='cart',
            field=models.TextField(default='{}'),
        ),
    ]
