# Generated by Django 4.1.4 on 2022-12-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_customer_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='likePosts',
            field=models.TextField(default='[]'),
        ),
    ]
