# Generated by Django 4.1.4 on 2022-12-31 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_customer_likeposts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='likePosts',
            new_name='likedPosts',
        ),
    ]
