# Generated by Django 4.0.5 on 2023-01-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_rename_likeposts_customer_likedposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='expoNotificationToken',
            field=models.TextField(default=''),
        ),
    ]
