# Generated by Django 4.0.5 on 2022-12-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='categories',
            field=models.TextField(default='{"0": "Frozen", "1": "Canned", "2": "Vegetables"}'),
        ),
    ]
