# Generated by Django 4.0.5 on 2022-12-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.TextField(default=''),
        ),
    ]
