# Generated by Django 4.0.5 on 2022-12-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_store_banner_store_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='city',
            field=models.TextField(default='Norrköping'),
        ),
        migrations.AlterField(
            model_name='store',
            name='categories',
            field=models.TextField(default='{"0": "Frozen food", "1": "Canned food", "2": "Vegetables", "3": "other"}'),
        ),
    ]
