# Generated by Django 4.0.5 on 2022-12-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_store_city_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='fave',
            field=models.IntegerField(default=0),
        ),
    ]
